engine/wiki/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('wiki.views',
    ('edit/(?P<name>.*)$', 'edit'),
    ('delete/(?P<name>.*)$', 'delete'),                       
    ('(?P<name>.*)$', 'view'),
    ('^$', 'view'),
)

engine/wiki/models.py
from datetime import datetime
from tagging.fields import TagField
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from parser import wikify


class Page(models.Model):
    name = models.CharField(max_length=255)
    content = models.TextField()
    rendered = models.TextField()
    modified = models.DateTimeField(default=datetime.now)
    author = models.ForeignKey(User, null=True)
    tags = TagField()

    class Meta:
        ordering = ('name', )

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        wiki_root = reverse('wiki.views.view')
        self.rendered = wikify(self.content, wiki_root)
        self.modified = datetime.now()
        super(Page, self).save(*args, **kwargs)

    def get_tag_list(self):
        return parse_tag_input(self.tags)

    def get_path(self):
        wiki_root = reverse('wiki.views.view')
        path = '/'.join(filter(None, self.tags.split(' ')))
        return wiki_root + path

engine/wiki/forms.py
from django import forms as forms
from models import Page


class PageForm(forms.Form):
    name = forms.CharField(max_length=255)
    content = forms.CharField(widget=forms.Textarea())

engine/wiki/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.utils.http import urlquote
from forms import PageForm
from models import Page
from tagging.models import Tag, TaggedItem


def edit(request, name):
    if not request.user.is_authenticated():
        raise Http404

    page = get(Page, name, True)

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if not page:
                page = Page()
            page.name = form.cleaned_data['name']
            page.content = form.cleaned_data['content']
            page.author = request.user
            page.tags = ' '.join(filter(None, name.split('/')))
            page.save()
            return HttpResponseRedirect('%s' % urlquote(page.get_path()))
    else:
        if page:
            form = PageForm(initial=page.__dict__)
        else:
            form = PageForm(initial={'name': name})
    return render_to_response('edit.html', {'form': form})


def delete(request, name):
    if not request.user.is_authenticated():
        raise Http404

    page = get(Page, name, True)

    if page:
        page.delete()
    else:
        raise Http404
    return HttpResponseRedirect('%s' % urlquote(name))


def view(request, name):
    if name == '':
        name = 'index'

    page = get(Page, name, True)
    pages = [page] if page else get(Page, name)

    if len(pages) == 0 and not request.user.is_authenticated():
        raise Http404

    return render_to_response('view.html', {'pages': pages,
                                            'name': name,
                                            'user': request.user})


def get(model, name, precise=False):
    tags = ' '.join(filter(None, name.split('/')))
    objects = TaggedItem.objects.get_by_model(model, tags)
    tag_set = str_to_set(tags)
    if precise:
        items = filter(lambda i: str_to_set(i.tags) == tag_set, objects)
        return items.pop() if len(items) == 1 else None
    else:
        return filter(lambda i: str_to_set(i.tags) >= tag_set, objects)


def str_to_set(s):
    return set(s.split(' '))

engine/wiki/templates/edit.html
{% extends 'base.html' %}

{% block content %}
	<h1>Edit</h1>
	<form action="" method="post">
		<div class="field_wrapper required{% if form.name.errors %} errors{% endif %}" id="field_name">
			<label for="id_name" class="field_name"><strong>Page name</strong></label>
			{% if form.name.errors %}{{ form.name.errors }}{% endif %}
			<div class="field text_input">
				{{ form.name }}
			</div>
		</div>
		<div class="field_wrapper required{% if form.content.errors %} errors{% endif %}" id="field_content">
			<label for="id_content" class="field_name"><strong>Content</strong></label>
			{% if form.content.errors %}{{ form.content.errors }}{% endif %}
			<div class="field textarea">
				{{ form.content }}
			</div>
		</div>
		<div class="submit">
			<input type="submit" value="Save" />
		</div>
		<div>
		<a href="http://creoleparser.googlepages.com/CheatSheetPlus.html" target="_blank">Help</a>
		</div>
	</form>
{% endblock %}

engine/wiki/templates/view.html
{% extends 'base.html' %}
{% block content %}
{% if pages %}
  {% for page in pages %}
    {% if page.name %}
<h3><a href="{{ page.get_path }}">{{ page.name|safe }}</a></h3>
    {% endif %}
    {{ page.rendered|safe }}
    {% if user.is_authenticated %}
> <a href="/edit/{{ page.get_path }}">Edit</a> | <a href="/delete/{{ page.get_path }}">Delete</a><hr/>
    {% endif %}
  {% endfor %}
{% else %}
  {% if user.is_authenticated %}
> <a href="/edit/{{ name }}">Create</a>
  {% endif %}
{% endif %}
{% endblock %}